### PR TITLE
Added procps package to dockerfile

### PR DESCRIPTION
**Pull request by keremavci**
Possible fix to  https://issues.apache.org/jira/browse/STORM-840

### CODE REVIEW

**Comment by 31z4** [comment]
According to the upstream issue the problem was caused by missing `kill` command. The image currently has this command
```
$ docker run -it --rm storm which kill
/bin/kill
```
Please elaborate why you `procps` is needed.

**Comment by keremavci** [comment]
I've tried the same command, but it returns nothing.

```
root@instance:~# docker run -it --rm storm which kill
root@instance:~# 
```

I've checked /bin/kill but there is no /bin/kill inside container image

```
root@50000b9f5341:/apache-storm-2.0.0# ls /bin/kill
ls: cannot access '/bin/kill': No such file or directory

```
Here you can check image id and other details;

```
root@instance:~# docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
storm                           latest              6e329d8cb370        10 days ago         571MB
```

**Comment by kirmandi** [comment]
the issue is not based on `kill` alone, since it first requires the PID which supervisor wants to retrieve by executing `ps`

have verified and found the same solution for this issue, in order to fix issue of not beeing able to kill topologies.

**Comment by tahaozket** [comment]
@kirmandi you are right, procps package also includes ps.

`The package includes the programs ps, top, vmstat, w, kill, free, slabtop, and skill.`

**Comment by bitsowit** [comment]
I use the storm2.0.0 docker, has same err. ps command doesn't work in the docker container.
@31z4 
when kill topo, need use ps first. 
If not install procps, storm supervisor will crash

java.io.IOException: Cannot run program "ps": error=2, No such file or directory

**Comment by 31z4** [comment]
Thank you all for the explanation and feedback 🙏 @keremavci I'm happy to merge once you resolve the conflicts.

**Review by kirmandi — APPROVED** [review]

**Comment by keremavci** [comment]
I’ve resolved the conflict.

**Pull request merged**
