### PR TITLE
Set hostname on nimbus

### PR DESCRIPTION
**Pull request by edbo**
When running this command:

```
storm  jar target/file-1.0-SNAPSHOT-jar-with-dependencies.jar com.somecompany.TestTopology test
```

I get this error when 

```
448  [main] INFO  o.a.s.StormSubmitter - Generated ZooKeeper secret payload for MD5-digest: -7340068425218594486:-5911778086654076904
501  [main] INFO  o.a.s.s.a.AuthUtils - Got AutoCreds []
Exception in thread "main" java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException: java.net.UnknownHostException: ee3f313730d9
	at org.apache.storm.security.auth.TBackoffConnect.retryNext(TBackoffConnect.java:64)
	at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:56)
	at org.apache.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:99)
	at org.apache.storm.security.auth.ThriftClient.<init>(ThriftClient.java:69)
	at org.apache.storm.utils.NimbusClient.<init>(NimbusClient.java:106)
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:78)
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:371)
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:311)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:157)
	at com.bitgamelabs.LiveTransactionTopology.main(LiveTransactionTopology.java:29)
Caused by: org.apache.storm.thrift.transport.TTransportException: java.net.UnknownHostException: ee3f313730d9
	at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:226)
	at org.apache.storm.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
	at org.apache.storm.security.auth.SimpleTransportPlugin.connect(SimpleTransportPlugin.java:103)
	at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:53)
	... 9 more
Caused by: java.net.UnknownHostException: ee3f313730d9
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:221)
```

### CODE REVIEW

**Comment by 31z4** [comment]
@edbo do you run the above command from your host? And your config is pointing to the dockerized Storm, right?

**Comment by edbo** [comment]
I haven't set a local storm config actually. Do you have an example of such a config that works without setting a host?

To be clear the above happens if I don't use this patch. If I do use the patch the exact same command runs fine.

**Comment by 31z4** [comment]
@edbo Sorry, I still didn't get that. From where do you run the command?

**Comment by edbo** [comment]
That's from the root directory of the project I'm working from. I guess I'm assuming it's not my environment because the error is resolvable by setting the hostname. Definitely strange that yours appears to work straight out of the box. I'd expect our hopefully identical containers to behave the same!

**Comment by 31z4** [comment]
@edbo sorry for the radio silence! I still don't understand how to reproduce your issue.
What commands do you run before running
`storm  jar target/file-1.0-SNAPSHOT-jar-with-dependencies.jar com.somecompany.TestTopology test`?
From where do you run the above command? From your host machine or from the running container?

**Comment by edbo** [comment]
This is all from the host machine.

1) `docker-compose up -d`
2) `storm jar target/file-1.0-SNAPSHOT-jar-with-dependencies.jar com.somecompany.TestTopology test`

**Pull request closed without merging**
